accessKeyId: accessKeyId
accessKeySecret: accessKeySecret
log:
  path: .\log
  level: debug # debug,info,warn,error
  develop: true # 开发者模式，开启后会输出代码文件和堆栈信息
ipv4_check_url: 4.ipw.cn #ipv4.icanhazip.com
ipv6_check_url: 6.ipw.cn #ipv6.icanhazip.com
interval: 60
broadband_retry: 1
cache: true
dnshost:
  - dnsname: dns
    ipv4_en: false
    ipv6_en: true
  - dnsname: ns1
    ipv4_en: false
    ipv6_en: true